### ISSUE TITLE
java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedREST#12]
#### Issue type:

- :bug: Bug

____

#### Short description:

it crashes

#### Steps to reproduce the problem:

1. ...Create a new world

#### Expected behaviour:

to not crash
____

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

https://paste.dimdev.org/ujotinigal.mccrash

**Comment by rubensworks** [comment]
This means that the port you are trying to run the HTTP server on is already taken. You should change it in the config file.

**Comment by Pival81** [comment]
Actually this seems to happen a lot after crashing with vanillafix.
My guess is that when I first generate/enter a world the rest server is initialized, but is not closed when the game crashes.
And since Vanillafix lets me continue to play after a crash, that address is considered already used, and crashes right after.
But then, this is just my guess.
I noticed this is solved by restarting the game instead of continuing to play, but with large packs it's a pain to have to restart just for this bug.
