### ISSUE TITLE
How i can extract only one value?

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/IntegratedREST#7]
#### Issue type:

- :question: Question

____

#### Question:

i wan´t terminal to not print whole json, but only one value. i try to found it for hours. 
i have simple setup with one redstone reader, and i want to get only the signal strengh. not loads of things like position, value type... in terminal.

**Comment by rubensworks** [comment]
It's JSON, so you can just use a JSON parser (like the one from Node.js), to extract parts of it.

**Comment by matyklug18** [comment]
I google almost half hour, and i cant find any tutorial. Can you please tell me where to find it?

**Comment by rubensworks** [comment]
First link in google: https://stackoverflow.com/questions/2933126/what-are-good-cli-tools-for-json

I'm not your search engine...

<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/2933126/what-are-good-cli-tools-for-json">What are good CLI tools for JSON?</a></strong></div><div>General Problem

Though I may be diagnosing the root cause of an event, determining how many users it affected, or distilling timing logs in order to assess the performance and throughput impact of a </div></blockquote>
